language: julia
sudo: required
os:
  - linux
  # - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
  fast_finish: true
  # allow_failures:
  # - julia: nightly

addons:
  apt:
    packages:
      - xvfb
      - xauth
      - libgtk-3-0

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("Cellular")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Cellular")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

before_script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/ChristianKurz/REPLGamesBase.jl.git")); Pkg.build("REPLGamesBase")'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/FielddocTables.jl")); Pkg.build("FielddocTables")'
  - $TESTCMD -e 'using Pkg;
                 Pkg.add("ImageMagick"); 
                 Pkg.build("ImageMagick"); 
                 Pkg.add("Blink"); 
                 Pkg.build("Blink"); 
                 using Blink;
                 Blink.AtomShell.install();'
script: 
  - $TESTCMD -e 'using Pkg; Pkg.test("Cellular"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - $TESTCMD --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                                   Pkg.instantiate(); include("docs/make.jl")'
      after_success: skip
