## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  # - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# matrix
 # allow_failures:
 # - julia: nightly

addons:
  apt:
    packages:
      - xvfb
      - xauth
      - libgtk-3-0

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/ChristianKurz/REPLGamesBase.jl.git")); Pkg.build("REPLGamesBase")'
  - $TESTCMD -e 'using Pkg;
                 Pkg.add("ImageMagick"); 
                 Pkg.build("ImageMagick"); 
                 using ImageMagick;
                 Pkg.add("Blink"); 
                 Pkg.build("Blink"); 
                 using Blink;
                 Pkg.add(PackageSpec(url=pwd())); 
                 Pkg.build("Cellular"); 
                 using Blink;
                 Blink.AtomShell.install();
                 Pkg.test("Cellular"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("Cellular")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Cellular")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # update docs, add requires deps for optional docs
  - julia -e 'using Pkg; Pkg.add("Plots"); Pkg.add("FileIO"); Pkg.add("Documenter"); Pkg.checkout("Documenter")'
  - $TESTCMD -e 'using Pkg; cd(Pkg.dir("Cellular")); ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs", "make.jl"))'
